# Git Conflict Resolver Configuration for CI Tests
# This file is used for testing the conflict resolver action

rules:
  # Test rule for package-lock.json
  - paths: 'package-lock.json'
    strategy: 'theirs'
    description: 'Accept incoming package-lock.json changes'

  # Test rule for generated files
  - paths: '*.generated.ts'
    strategy: 'ours'
    description: 'Keep our generated TypeScript files'

  # Test rule for dist files
  - paths: 'dist/**/*'
    strategy: 'ours'
    description: 'Keep our distribution files'
