# Git Conflict Resolver Configuration for CI Tests
# This file is used for testing the conflict resolver action

rules:
  # Test rule for package-lock.json
  - paths: 'package-lock.json'
    strategy: 'theirs'

  # Test rule for generated files
  - paths: '*.generated.ts'
    strategy: 'ours'

  # Test rule for dist files
  - paths: 'dist/**/*'
    strategy: 'ours'

  # Example with conflict_type: only apply when both sides modified
  - paths: 'src/**/*.test.ts'
    conflict_type: 'both-modified'
    strategy: 'theirs'

  # Example with conflict_type: handle files added by both sides
  - paths: 'docs/**/*.md'
    conflict_type: 'both-added'
    strategy: 'theirs'

  # Example with manual strategy: require human review
  - paths: '.github/workflows/*.yml'
    strategy: 'manual'

  # Example with manual strategy and conflict_type
  - paths: '**/*.config.js'
    conflict_type: 'both-modified'
    strategy: 'manual'

  # === Test conflict files rules ===
  
  # JSON files - use incoming changes
  - paths: 'test-conflict-files/*.json'
    strategy: 'theirs'
    conflict_type: 'both-modified'
  
  # Markdown files - keep our version
  - paths: 'test-conflict-files/*.md'
    strategy: 'ours'
    conflict_type: 'both-modified'
  
  # TypeScript files - use incoming changes for both-modified
  - paths: 'test-conflict-files/test.ts'
    strategy: 'theirs'
    conflict_type: 'both-modified'
  
  # Critical TypeScript file - require manual review
  - paths: 'test-conflict-files/critical.ts'
    strategy: 'manual'
    conflict_type: 'both-modified'
  
  # Config YAML files - require manual review
  - paths: 'test-conflict-files/*.config.yml'
    strategy: 'manual'
  
  # Binary files resolution strategies
  - paths: 'test-conflict-files/*.png'
    strategy: 'theirs'
  
  - paths: 'test-conflict-files/*.pdf'
    strategy: 'ours'
  
  - paths: 'test-conflict-files/*.zip'
    strategy: 'theirs'
  
  # Note: Files without rules (undefined-rule.txt, special-case.xml) 
  # will remain unresolved with conflict markers
